using FFTW: FFTW, fft, fftshift
using ProgressMeter: ProgressMeter, Progress, next!
using Random: Random


"""
Time-domain acceleration waveform generated by superimposing random sinusoids.

```julia
trace = AccelerationTrace(
    psd;
    tlist, f_band_min, f_band_max, n_oscillators, rng, target_rms,
    show_progress)
```

superimposes `n_oscillators` random sinusoids with physically derived amplitudes
Aₖ = √(2·S(fₖ)·Δf/M) and holds the resulting time-domain waveform and
oscillator parameters. When `target_rms` is given, all arrays are rescaled by
`eta` = target_rms/actual_rms to enforce the RMS exactly. Use
[`AccelerationSpectrum`](@ref) to compute the FFT spectrum; write with
[`write_acceleration_trace`](@ref).

# Keyword Arguments

- `tlist`: time grid (s); typically a uniform `range` or `Vector{Float64}`,
  but any `AbstractVector` is accepted — oscillators are evaluated at each
  `tlist[it]`, so non-uniform grids work. For [`AccelerationSpectrum`](@ref)
  the grid must be uniform (asserted there).
- `f_band_min`, `f_band_max`: frequency band for oscillator sampling (Hz)
- `n_oscillators`: number of random sinusoids to superimpose
- `rng`: random number generator; any `AbstractRNG`; defaults to
  `Random.default_rng()` (non-fixed seed). Pass a `Ran2State` for legacy
  reproducible output.
- `target_rms`: desired RMS acceleration (m/s²); if `nothing` (default), no
  rescaling is applied and the raw Monte Carlo RMS is kept.
- `show_progress`: if `true`, display a progress bar while drawing oscillators;
  default `true`

# Fields

- `tlist`: time grid (s), length `n_samples`; typically uniform but may be
  arbitrary — [`AccelerationSpectrum`](@ref) asserts uniformity
- `acceleration`: acceleration waveform (m/s²), length `n_samples`
- `displacement`: displacement waveform (m), length `n_samples`; satisfies
  ``ẍ = a`` entry-by-entry
- `oscillators`: 3 × `n_oscillators` matrix of
  (amplitude Aₖ (m/s²), frequency fₖ (Hz), phase φₖ (rad))
- `f_band_min`, `f_band_max`: noise band limits (Hz)
- `rms`: actual RMS of `acceleration` (m/s²)
- `n_candidates`: total random candidates drawn during oscillator selection
- `eta`: rescaling factor applied to all arrays; 1.0 if `target_rms=nothing`,
  otherwise target_rms / raw_rms
"""
struct AccelerationTrace
    tlist::Vector{Float64}
    acceleration::Vector{Float64}
    displacement::Vector{Float64}
    oscillators::Matrix{Float64}
    f_band_min::Float64
    f_band_max::Float64
    rms::Float64
    n_candidates::Int
    eta::Float64
end


function AccelerationTrace(
    psd::PSDData;
    tlist,
    f_band_min::Float64,
    f_band_max::Float64,
    n_oscillators::Int,
    rng::Random.AbstractRNG = Random.default_rng(),
    target_rms::Union{Float64,Nothing} = nothing,
    show_progress::Bool = true,
)
    n_samples    = length(tlist)
    Δf          = f_band_max - f_band_min
    acceleration = zeros(Float64, n_samples)
    displacement = zeros(Float64, n_samples)
    oscillators  = zeros(Float64, 3, n_oscillators)  # rows: Aₖ (m/s²), fₖ (Hz), φₖ (rad)
    n_candidates = 0
    n_accepted   = 0

    prog = Progress(n_oscillators; desc = "Oscillators: ", enabled = show_progress)
    while n_accepted < n_oscillators

        n_candidates += 1
        f = rand(rng) * f_band_max

        if f_band_min <= f <= f_band_max

            n_accepted += 1
            next!(prog)

            ϕ = 2π * rand(rng)

            S = psd(f)  # interpolated PSD value S(fₖ) in (m/s²)²/Hz

            # Physical amplitude: each of the M oscillators occupies an expected
            # bin of width Δf/M.  Requiring ⟨aₖ² cos²⟩ = ⟨aₖ²⟩/2 = S(fₖ)·Δf/M
            # gives aₖ = √(2·S(fₖ)·Δf/M) in m/s².
            a = sqrt(2 * S * Δf / n_oscillators)
            ω = 2π * f
            x₀ = a / ω^2  # displacement amplitude: xₖ(t) = -x₀ cos(ωₖt + φₖ)

            oscillators[1, n_accepted] = a
            oscillators[2, n_accepted] = f
            oscillators[3, n_accepted] = ϕ

            # Accumulate oscillator contributions at each time point.
            #
            # acceleration: a(t) = Σₖ aₖ cos(ωₖ t + φₖ)  [m/s²]
            # displacement: x(t) = Σₖ xₖ(t)              [m]
            #   xₖ satisfies ẍₖ = aₖ cos(ωₖ t + φₖ); integrating twice gives
            #   xₖ(t) = -(aₖ/ωₖ²) cos(ωₖ t + φₖ) = -x₀ cos(ωₖ t + φₖ).
            for it = 1:n_samples
                cos_val          = cos(ω * tlist[it] + ϕ)
                acceleration[it] += a * cos_val
                displacement[it] -= x₀ * cos_val
            end

        end

    end

    # -- RMS normalization ---------------------------------------------------
    #
    # By construction, E[⟨a²⟩] = Σₖ aₖ²/2 = Σₖ S(fₖ)·Δf/M → ∫_band S(f) df
    # (law of large numbers, fₖ ~ Uniform[f_band_min, f_band_max]).
    # Therefore η = target_rms / actual_rms satisfies:
    #
    #   η ≈ 1               if target_rms = √∫_band S df  (band-limited RMS)
    #   η ≈ √(∫_full/∫_band) if target_rms = profile_rms = √∫_full S df
    #
    # Deviations from the expected value are O(1/√M) Monte Carlo noise.
    # If target_rms is given, multiply all arrays by η to enforce exact RMS.
    #
    actual_rms = sqrt(sum(abs2, acceleration) / n_samples)

    if !isnothing(target_rms)
        eta = target_rms / actual_rms
        acceleration .*= eta
        displacement .*= eta
        oscillators[1, :] .*= eta
        trace_rms = target_rms
    else
        eta = 1.0
        trace_rms = actual_rms
    end

    return AccelerationTrace(
        collect(Float64, tlist),
        acceleration,
        displacement,
        oscillators,
        f_band_min,
        f_band_max,
        trace_rms,
        n_candidates,
        eta,
    )
end


function Base.show(io::IO, trace::AccelerationTrace)
    n_samples = length(trace.tlist)
    n_oscillators = size(trace.oscillators, 2)
    print(
        io,
        "AccelerationTrace(n_samples=",
        n_samples,
        ", n_oscillators=",
        n_oscillators,
        ", rms=",
        trace.rms,
        ")"
    )
end


function Base.show(io::IO, ::MIME"text/plain", trace::AccelerationTrace)
    n_samples = length(trace.tlist)
    n_oscillators = size(trace.oscillators, 2)
    dt = trace.tlist[2] - trace.tlist[1]
    println(io, "AccelerationTrace with ", n_oscillators, " oscillators")
    println(io, "   n_samples       : ", n_samples)
    println(io, "   dt (s)          : ", dt)
    println(io, "   f_band_min (Hz) : ", trace.f_band_min)
    println(io, "   f_band_max (Hz) : ", trace.f_band_max)
    println(io, "   n_candidates    : ", trace.n_candidates)
    println(io, "   rms (m/s²)      : ", trace.rms)
    print(io, "   eta (target RMS / actual) : ", trace.eta)
end


"""
Normalized two-sided FFT spectrum of an [`AccelerationTrace`](@ref).

```julia
spectrum = AccelerationSpectrum(trace)
```
computes the FFT of `trace.acceleration`, normalizes so that ∫|F(f)|²df = rms²,
reorders into a two-sided layout, and holds the result. Requires `trace.tlist`
to be uniform. See [`write_acceleration_spectrum`](@ref) and
[`check_acceleration_spectrum`](@ref).

# Fields
- `freq_axis`: frequency axis of two-sided spectrum (Hz), length `n_samples + 1`;
  uniform with spacing df = freq_axis[2] − freq_axis[1]
- `spectrum`: complex spectral amplitude (m/s²/√Hz), length `n_samples + 1`
- `rms`: RMS computed from the spectrum as √(∑|F(f)|²·df) (m/s²); should match
  the source trace RMS — checked by [`check_acceleration_spectrum`](@ref)
"""
struct AccelerationSpectrum
    freq_axis::Vector{Float64}
    spectrum::Vector{ComplexF64}
    rms::Float64
end


function AccelerationSpectrum(trace::AccelerationTrace)
    n_samples = length(trace.tlist)
    dt = trace.tlist[2] - trace.tlist[1]
    @assert all(
        abs(trace.tlist[it] - trace.tlist[it-1] - dt) ≤ 1e-10 * dt for it = 2:n_samples
    ) "AccelerationSpectrum requires a uniform time grid"
    f_max = 1.0 / dt
    df = f_max / n_samples

    # FFTW uses the same unnormalized DFT convention
    fft_output = fft(trace.acceleration)

    # Normalize spectrum so that ∫|F(f)|² df = rms²
    spectrum_scale = sqrt(1.0 / df) / n_samples
    fft_output .*= spectrum_scale

    # Reorder to two-sided (symmetric) layout centered at DC.
    # fftshift converts FFTW's [DC, pos freqs, Nyquist, neg freqs] to
    # [Nyquist, neg freqs, DC, pos freqs]; appending shifted[1] duplicates
    # the Nyquist bin at both ends so the spectrum runs from -f_max/2 to +f_max/2.
    shifted   = fftshift(fft_output)
    spectrum  = [shifted; shifted[1]]
    freq_axis = collect(range(-f_max / 2, f_max / 2; length = n_samples + 1))

    # Compute rms independently from the spectrum so it can be checked against
    # trace.rms.  The normalization guarantees sum(|F|²)·df = rms²; excluding
    # the duplicate Nyquist endpoint (present at both spectrum[1] and
    # spectrum[end]) gives the correct n_samples-point sum.
    spec_rms = sqrt(sum(abs2, spectrum[1:(end-1)]) * df)

    return AccelerationSpectrum(freq_axis, spectrum, spec_rms)
end


function Base.show(io::IO, spectrum::AccelerationSpectrum)
    n_samples = length(spectrum.freq_axis) - 1
    df = spectrum.freq_axis[2] - spectrum.freq_axis[1]
    print(
        io,
        "AccelerationSpectrum(n_samples=",
        n_samples,
        ", df=",
        df,
        ", rms=",
        spectrum.rms,
        ")"
    )
end


function Base.show(io::IO, ::MIME"text/plain", spectrum::AccelerationSpectrum)
    n_samples = length(spectrum.freq_axis) - 1
    df = spectrum.freq_axis[2] - spectrum.freq_axis[1]
    println(io, "AccelerationSpectrum with ", n_samples, " samples")
    println(io, "   df (Hz)  : ", df)
    println(io, "   f_min (Hz): ", spectrum.freq_axis[1])
    println(io, "   f_max (Hz): ", spectrum.freq_axis[end])
    print(io, "   rms (m/s²): ", spectrum.rms)
end

rms(trace::AccelerationTrace) = trace.rms

function rms(spectrum::AccelerationSpectrum; f_min::Float64 = 0.0, f_max::Float64 = Inf)
    df = spectrum.freq_axis[2] - spectrum.freq_axis[1]
    rms_sq = 0.0
    for (f, s) in zip(spectrum.freq_axis, spectrum.spectrum)
        f_min <= abs(f) <= f_max || continue
        rms_sq += abs2(s) * df
    end
    return sqrt(rms_sq)
end


"""
Resample an [`AccelerationTrace`](@ref) at an arbitrary time grid.

```julia
resampled = resample_acceleration_trace(trace; tlist=0:1e-3:10.0)
```
re-evaluates the oscillator superposition from `trace.oscillators` at each
point in `tlist` and returns a new [`AccelerationTrace`](@ref) with the same
oscillator parameters (`eta = 1.0`, `rms` is the actual RMS of the resampled
waveform). Write the result with [`write_acceleration_trace`](@ref).

# Keyword Arguments
- `tlist`: new time grid (s); may be uniform or non-uniform
- `show_progress`: if `true`, display a progress bar while evaluating time
  points; default `true`
"""
function resample_acceleration_trace(
    trace::AccelerationTrace;
    tlist,
    show_progress::Bool = true
)
    n_oscillators = size(trace.oscillators, 2)
    n_samples     = length(tlist)
    acceleration  = zeros(Float64, n_samples)
    displacement  = zeros(Float64, n_samples)

    a = trace.oscillators[1, :]
    ω = 2π .* trace.oscillators[2, :]
    φ = trace.oscillators[3, :]
    x₀ = a ./ ω .^ 2

    prog = Progress(n_samples; desc = "Resampling: ", enabled = show_progress)
    for it = 1:n_samples

        t   = tlist[it]
        acc = 0.0
        x   = 0.0
        for i_osc = 1:n_oscillators
            cos_val = cos(ω[i_osc] * t + φ[i_osc])
            acc += a[i_osc] * cos_val
            x -= x₀[i_osc] * cos_val
        end
        acceleration[it] = acc
        displacement[it] = x
        next!(prog)

    end

    trace_rms = sqrt(sum(abs2, acceleration) / n_samples)

    return AccelerationTrace(
        collect(Float64, tlist),
        acceleration,
        displacement,
        trace.oscillators,
        trace.f_band_min,
        trace.f_band_max,
        trace_rms,
        trace.n_candidates,
        1.0,
    )
end
